name: Compile LaTeX and Upload Artifact

on:
  push:
    branches:
      - main

jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Compile LaTeX Document (First Run)
        uses: xu-cheng/latex-action@v2
        with:
          root_file: CW_Final_Assignment.tex

      - name: Compile LaTeX Document (Second Run)
        uses: xu-cheng/latex-action@v2
        with:
          root_file: CW_Final_Assignment.tex

      - name: Upload Compiled PDF as Artifact
        uses: actions/upload-artifact@v3
        with:
          name: CW_Final_Assignment
          path: ./CW_Final_Assignment.pdf
